### ISSUE TITLE
Errors upon loading game pages

### ISSUE THREAD

**Issue by ellisspice** [e-ucm/rage-analytics#34]
Upon loading a page for a game the following errors appear:

![gamepageloaderrors1](https://cloud.githubusercontent.com/assets/18191083/20005237/ff0027d4-a288-11e6-85a4-4533dad1c1c6.PNG)
![gamepageloaderrors2](https://cloud.githubusercontent.com/assets/18191083/20005238/00bf6f30-a289-11e6-9723-1c97a252d820.PNG)

A different version of the same page can also be seen for a short time before these errors and a different layout loads.

**Comment by gorco** [comment]
The 403 erros are normal. we make developers and teacher requests for all users. With these we check the permissions. We'll remove it.
And we'll check the others errors (thrown by kibana). Have you noticed anything that is not working in that case?
