### ISSUE TITLE
Possible to reach broken sign in page whilst signed in

### ISSUE THREAD

**Issue by ellisspice** [e-ucm/rage-analytics#36]
The below screenshot was caused by going to api/proxy/afront just after signing in.

![postloginerror](https://cloud.githubusercontent.com/assets/18191083/20005322/8f2e5434-a289-11e6-9a7d-73f7a94c0870.PNG)

**Comment by gorco** [comment]
We know the problem. You have to use "api/proxy/afront/" (with ending "/")
The problem comes from proxy module in A2. We have to look for other modules but for now is not a priority.

**Comment by RotaruDan** [comment]
Fixed here https://github.com/e-ucm/rage-analytics-frontend/pull/83
