### ISSUE TITLE
Container elastic5 failed to launch

### ISSUE THREAD

**Issue by cferguson-uu** [e-ucm/rage-analytics#41]
I´m trying to run this in an Ubuntu virtual machine and have installed everything but when I go to launch, I get the same error each time: 

Waiting for redis to be up at 172.18.0.5:6379 ... 
 OK - redis:6379 (Redis) reachable after 0s
Waiting for elastic to be up at 172.18.0.7:9317 ... ........
 OK - elastic:9317 (ElasticSearch) reachable after 8s
Container elastic5 failed to launch.
Please run './rage-analytics.sh report' to file a new issue to help us help you.

Any idea of how I can fix this please?

Kind Regards,
Chris

[report-2017_03_24_10_14.txt](https://github.com/e-ucm/rage-analytics/files/867463/report-2017_03_24_10_14.txt)

[report-2017_03_24_10_55.txt](https://github.com/e-ucm/rage-analytics/files/867462/report-2017_03_24_10_55.txt)

**Comment by imartinezortiz** [comment]
Hi Chris,

  Usual suspects are:

- Your VM is below the minimum required specs (see [README.md](https://github.com/e-ucm/rage-analytics/blob/master/README.md)) or
- You need to have a look to [the installation guide](https://github.com/e-ucm/rage-analytics/wiki/Installation-Guide#simple-usage). Particularly developers miss the kernel parameter configuration that is required by ES, if you do not configure it (preferably in a permanent way) ES literally refuses to start.

**Comment by cferguson-uu** [comment]
Ah, there we are. Sorry, didn't realise my RAM was only set to 1024mb!

**Comment by imartinezortiz** [comment]
Great that you finally figure it out
