### ISSUE TITLE
503 responses from API to front end requests

### ISSUE THREAD

**Issue by scottbw** [e-ucm/rage-analytics#62]
I set up another instance on Ubuntu on Azure while I see if a Mac version will work. It all installed OK, and I created users with developer and teacher roles, and create a course and a game. However, a few minutes later, both the game and course vanished with no error messages. Looking into the JS console I can see that this is because the API is returning 503 for most requests.

E.g.:

GET http://40.115.114.11:3000/api/proxy/gleaner/games/my 503 (Service Unavailable)

Similar for viewing as a teacher. POSTs also return 503.

Looks like the backend may have encountered an error and crashed out:

     Name                    Command               State                          Ports
--------------------------------------------------------------------------------------------------------------
a2                npm run docker-start             Up       0.0.0.0:3000->3000/tcp
back              npm run docker-start             Exit 1
elastic5          /bin/bash bin/es-docker          Up       127.0.0.1:9200->9200/tcp, 127.0.0.1:9300->9300/tcp
front             npm run docker-start             Up       127.0.0.1:3350->3350/tcp
kibana            /docker-entrypoint.sh /usr ...   Up       127.0.0.1:5601->5601/tcp
kzk               supervisord -n                   Up       127.0.0.1:2181->2181/tcp, 127.0.0.1:9092->9092/tcp
mongo             docker-entrypoint.sh mongod      Up       27017/tcp
nimbus            /bin/sh -c ./goStorm.sh nimbus   Up       127.0.0.1:6627->6627/tcp
persister         npm run docker-start             Up       127.0.0.1:3003->3003/tcp
rage_realtime_1   /usr/local/bin/mvn-entrypo ...   Exit 0
redis             docker-entrypoint.sh redis ...   Up       6379/tcp
supervisor        /bin/sh -c ./goStorm.sh su ...   Up       6700/tcp, 6701/tcp, 6702/tcp, 6703/tcp
teas              npm run docker-start             Up       3350/tcp, 127.0.0.1:3550->3550/tcp

**Comment by RotaruDan** [comment]
The problem seems to be this:

back npm run docker-start Exit 1

Can you please run

./rage-analytics.sh logs back

And dump the result on a comment here please.

Thank you very much.

**Comment by scottbw** [comment]
I'll try and do that later today.

**Comment by scottbw** [comment]
I'd actually restarted the VM and run the launch script again so not sure if the log dump will be that useful, but actually I have a problem here in that elastic is taking a VERY long time to start up.

(Is there a function for doing a fast restart in case the VM needs to be restarted? Or is doing the whole launch script the only approach?)

EDIT: My fault, I forgot to reset map size... but it looks like the log was reset on relaunch so there isn't anything useful in it.

**Comment by scottbw** [comment]
I restarted the VM, created a new activity, and immediately the backend crashed. Log attached.
[back-log.txt](https://github.com/e-ucm/rage-analytics/files/2494983/back-log.txt)

**Comment by gorco** [comment]
There seems to be some problem with the kibana visualizations that are stored.

When you restart the containers and try again to create an activity, does it happen again?

**Comment by scottbw** [comment]
Yes, every time I create an activity, the backend crashes.

**Comment by RotaruDan** [comment]
Should be fixed in the next stable release or here: https://github.com/e-ucm/rage-analytics/issues/64#issuecomment-431333573
