### ISSUE TITLE
LTI Launch URL is "undefined"

### ISSUE THREAD

**Issue by scottbw** [e-ucm/rage-analytics#63]
After creating a class and entering the LTI secret, the LTI launch URL generated by the server contains "undefined" in the path and is not valid, e.g.:

http://rage.northeurope.cloudapp.azure.com:3000/api/login/launch/undefined/gleaner

**Comment by gorco** [comment]
In the last version of the interface there is a small bug that causes that variable to be undefined.
We will solve it throughout the morning, until then, in the default configuration, that variable should contain "afront".

**Comment by scottbw** [comment]
As in "http://rage.northeurope.cloudapp.azure.com:3000/api/login/launch/afront/gleaner"?

That also generates a 404.

Edit: It actually generates a 404 with content {"message":"Not Found"}

**Comment by RotaruDan** [comment]
Changes merged, should be fixed in the next stable release or here: https://github.com/e-ucm/rage-analytics/issues/64#issuecomment-431333573

**Comment by scottbw** [comment]
OK, I'll create a new issue on the launch not actually working.
