### ISSUE TITLE
Backend 1.7.0 has breaking API changes

### ISSUE THREAD

**Issue by scottbw** [e-ucm/rage-analytics#68]
Two so far:

POSTing a new activity now makes "offline" property mandatory

GETing an activity no longer contains the students[] and teachers[] arrays.

Both of these broke my implementation. The first was trivial to fix at my end, the latter has no obvious solution, so I'm reverting to 1.5.2.

**Comment by gorco** [comment]
The activities now use the participants of its parent class or a subgroup of users if it has created a group/grouping.

Now the model of the classes are:
{
        "_id": "5bcf594fb8cebaf2c0889640",
        "name": "class",
        "created": "2018-10-23T17:24:31.897Z",
        "participants": {
            "teachers": [
                "tea"
            ],
            "students": [
                "us1",
                "us2"
            ],
            "assistants": [
                "cxz"
            ]
        },
        "groups": [],
        "groupings": [],
        "externalId": []
}

And the model of the activities are:
{
        "_id": "5bd0925eb329dd4f21779073",
        "name": "asd2",
        "gameId": "5bbb5451d2bc03f2217259f9",
        "versionId": "5bbb5451d2bc03f2217259fa",
        "classId": "5bcf594fb8cebaf2c0889640",
        "rootId": "",
        "offline": false,
        "groups": [],
        "groupings": [],
        "created": "2018-10-24T15:40:14.563Z",
        "open": false,
        "visible": false,
        "allowAnonymous": false,
        "trackingCode": "5bd0925eb329dd4f21779073nfrchfq5r3"
    }

You can know the participants of an activity by consulting those of the parent class, or, in case the activity has assigned groups or groupings, by consulting the participants of these. 
More info at: https://github.com/e-ucm/rage-analytics/wiki/Groups-and-Groupings
